method: bayes
metric:
  name: accuracy
  goal: maximize
parameters:
  epochs:
    values: [5, 10]
  hidden_layers:
    values: [3, 4, 5]
  hidden_size:
    values: [32, 64, 128]
  weight_decay:
    values: [0, 0.0005, 0.5]
  learning_rate:
    values: [0.001, 0.0001]
  optimizer:
    values: ["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"]
  batch_size:
    values: [16, 32, 64]
  weight_init:
    values: ["random", "Xavier"]
  activation:
    values: ["sigmoid", "tanh", "ReLU"]
